/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";
import DiskLayout from "@/layouts/disk-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
  disk: DiskLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  init: () => import("@/views/_builtin/init/index.vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about: () => import("@/views/about/index.vue"),
  admin: () => import("@/views/admin/index.vue"),
  disk: () => import("@/views/disk/index.vue"),
  log_login: () => import("@/views/log/login/index.vue"),
  log_operation: () => import("@/views/log/operation/index.vue"),
  manage_dept: () => import("@/views/manage/dept/index.vue"),
  manage_dict: () => import("@/views/manage/dict/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_notice: () => import("@/views/manage/notice/index.vue"),
  manage_post: () => import("@/views/manage/post/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  manage_settings: () => import("@/views/manage/settings/index.vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
};
