/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 99
    }
  },
  {
    name: 'admin',
    path: '/admin',
    component: 'layout.base$view.admin',
    meta: {
      title: 'admin',
      i18nKey: 'route.admin',
      icon: 'mdi:monitor-dashboard',
      order: 1,
      fixedIndexInTab: 0,
      module: 'admin'
    }
  },
  {
    name: 'disk',
    path: '/disk',
    component: 'layout.disk$view.disk',
    meta: {
      title: 'disk',
      i18nKey: 'route.disk',
      icon: 'mdi:harddisk',
      order: 2,
      module: 'disk'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'init',
    path: '/init',
    component: 'layout.blank$view.init',
    meta: {
      title: 'init',
      i18nKey: 'route.init',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base',
    meta: {
      title: 'log',
      i18nKey: 'route.log',
      icon: 'carbon-cloud-logging',
      order: 4
    },
    children: [
      {
        name: 'log_login',
        path: '/log/login',
        component: 'view.log_login',
        meta: {
          title: 'log_login',
          i18nKey: 'route.log_login'
        }
      },
      {
        name: 'log_operation',
        path: '/log/operation',
        component: 'view.log_operation',
        meta: {
          title: 'log_operation',
          i18nKey: 'route.log_operation',
          icon: 'carbon-operations-record',
          order: 2
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.base$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon-cloud-service-management',
      order: 3,
      module: 'admin'
    },
    children: [
      {
        name: 'manage_dept',
        path: '/manage/dept',
        component: 'view.manage_dept',
        meta: {
          title: 'manage_dept',
          i18nKey: 'route.manage_dept',
          icon: 'carbon-development',
          order: 4
        }
      },
      {
        name: 'manage_dict',
        path: '/manage/dict',
        component: 'view.manage_dict',
        meta: {
          title: 'manage_dict',
          i18nKey: 'route.manage_dict',
          icon: 'iconoir-book',
          order: 6
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'carbon-menu',
          order: 3
        }
      },
      {
        name: 'manage_post',
        path: '/manage/post',
        component: 'view.manage_post',
        meta: {
          title: 'manage_post',
          i18nKey: 'route.manage_post',
          icon: 'carbon-ibm-z-processor-capacity-reference',
          order: 5
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon-user-role',
          order: 2
        }
      },
      {
        name: 'manage_settings',
        path: '/manage/settings',
        component: 'view.manage_settings',
        meta: {
          title: 'manage_settings',
          i18nKey: 'route.manage_settings',
          icon: 'carbon-settings-edit',
          order: 8
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'carbon-user',
          order: 1
        }
      }
    ]
  }
];
